### PR TITLE
Feat/create lit app

### LINKED ISSUE #10: Create new commands for generating lit protocol projects from templates
A set of commands which let you quickly bootstrap a front end project letting users pick to include various Lit Protocol packages.
- Lit Auth Client
- Contracts SDK
- PKP-Signers
- pkp-cosmos
- pkp-ethers

The `lit-node-client` package should be included by default in generated projects.

We should let users choose from various front end frameworks including:
- React
- NextJS

### PR DESCRIPTION
**Pull request by yhl125**
# WHAT
resolve #10 

- remove getlit from package.json(fix getlit@file:getlit-0.10.0.tgz failed to resolve)
- add NextJS page router template
- add NextJS app router template
- add React template
- add create-next-app command
- add create-react-app command

# HOW
`command`
```
bun run start create-react-app
```
```
bun run start create-next-app
```

### CODE REVIEW

**Comment by joshLong145** [comment]
@yhl125 Thank you so much! I will review in the upcoming days

**Comment by joshLong145** [comment]
This is awesome! thank you for putting it together. Here are a couple of notes from generating both a `react` and `next` project.

`React`
- When i run `getlit creat-react-app` I get an error when running the dev server
` Buffer is not defined`.
- When using `google OAuth` I found when running in development not setting the local server port to `3000` breaks the default dev redirection. 

 I was able to get around this by changing the `vite config`
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    global: {},
  },
  server: {
    port: 3000,
  },
  resolve: {
    alias: {
    },
  },
  plugins: [,
      react(),
  ],
  optimizeDeps: {
    esbuildOptions: {
        // Node.js global to browser globalThis
        define: {
            global: 'globalThis'
        },
        // Enable esbuild polyfill plugins
        plugins: [
            NodeGlobalsPolyfillPlugin({
                buffer: true
            })
        ]
    }
  }
});
```

`NextJS`
After running `getlit create-next-app` i get the following error when trying to run in dev mode:
```
⨯ upstream image response failed for /google.png TypeError: fetch is not a function
    at invokeRequest (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:18)
    at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:600:74
    at imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/image-optimizer.js:576:19)
    at DevServer.imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:595:20)
    at cacheEntry.imageResponseCache.get.incrementalCache (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:181:76)
    at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/response-cache/index.js:90:42
    at async /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/lib/batcher.js:41:32
 ⨯ upstream image response failed for /discord.png TypeError: fetch is not a function
    at invokeRequest (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:18)
    at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:600:74
    at imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/image-optimizer.js:576:19)
    at DevServer.imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:595:20)
    at cacheEntry.imageResponseCache.get.incrementalCache (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:181:76)
    at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/response-cache/index.js:90:42
    at async /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/lib/batcher.js:41:32
```

**Comment by a1ttech** [comment]
hey @yhl125 this is awesome, we'd love to feature this work in a blog post. What's your Telegram handle so we can coordinate specifics?

**Comment by yhl125** [comment]
> hey @yhl125 this is awesome, we'd love to feature this work in a blog post. What's your Telegram handle so we can coordinate specifics?

@yoonhlee

**Comment by joshLong145** [comment]
> > This is awesome! thank you for putting it together. Here are a couple of notes from generating both a `react` and `next` project.
> > `React`
> > 
> > * When i run `getlit creat-react-app` I get an error when running the dev server
> >   ` Buffer is not defined`.
> > * When using `google OAuth` I found when running in development not setting the local server port to `3000` breaks the default dev redirection.
> > 
> > I was able to get around this by changing the `vite config`
> > ```
> > import { defineConfig } from "vite";
> > import react from "@vitejs/plugin-react";
> > import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill";
> > 
> > // https://vitejs.dev/config/
> > export default defineConfig({
> >   define: {
> >     global: {},
> >   },
> >   server: {
> >     port: 3000,
> >   },
> >   resolve: {
> >     alias: {
> >     },
> >   },
> >   plugins: [,
> >       react(),
> >   ],
> >   optimizeDeps: {
> >     esbuildOptions: {
> >         // Node.js global to browser globalThis
> >         define: {
> >             global: 'globalThis'
> >         },
> >         // Enable esbuild polyfill plugins
> >         plugins: [
> >             NodeGlobalsPolyfillPlugin({
> >                 buffer: true
> >             })
> >         ]
> >     }
> >   }
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `NextJS` After running `getlit create-next-app` i get the following error when trying to run in dev mode:
> > ```
> > ⨯ upstream image response failed for /google.png TypeError: fetch is not a function
> >     at invokeRequest (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:18)
> >     at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:600:74
> >     at imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/image-optimizer.js:576:19)
> >     at DevServer.imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:595:20)
> >     at cacheEntry.imageResponseCache.get.incrementalCache (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:181:76)
> >     at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/response-cache/index.js:90:42
> >     at async /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/lib/batcher.js:41:32
> >  ⨯ upstream image response failed for /discord.png TypeError: fetch is not a function
> >     at invokeRequest (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:18)
> >     at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:600:74
> >     at imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/image-optimizer.js:576:19)
> >     at DevServer.imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:595:20)
> >     at cacheEntry.imageResponseCache.get.incrementalCache (/Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/next-server.js:181:76)
> >     at /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/server/response-cache/index.js:90:42
> >     at async /Users/joshlong/Documents/repos/forks/getlit/demo-next/node_modules/next/dist/lib/batcher.js:41:32
> > ```
> 
> `react` I fixed vite config using vite-plugin-node-polyfills instead esbuild-plugins
> 
> ```
> import { defineConfig } from 'vite';
> import react from '@vitejs/plugin-react';
> import { nodePolyfills } from 'vite-plugin-node-polyfills';
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   define: {
>     global: {},
>   },
>   resolve: {
>     alias: {},
>   },
>   plugins: [
>     nodePolyfills({
>       globals: {
>         Buffer: true,
>       },
>     }),
>     ,
>     react(),
>   ],
> });
> ```
> 
> and chage port
> 
> ```
> export const ORIGIN =
>   import.meta.env.VITE_ENV === "production"
>     ? `https://${DOMAIN}`
>     : `http://${DOMAIN}:5173`;
> ```
> 
> `NextJS` this is issue with .next/cache .next/cache/images is not created on initial rendering of run dev After a refresh or page routing it works fine So I moved initial page to /signup, and make initial page to router.replace('/signup')

Makes sense, After pulling your changes everything is looking good, outside of this issue i am still seeing with the `react` project gen:
```
 upstream image response failed for /google.png TypeError: fetch is not a function
    at invokeRequest (/Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:18)
    at /Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/server/next-server.js:600:74
    at imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/server/image-optimizer.js:576:19)
    at DevServer.imageOptimizer (/Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/server/next-server.js:595:20)
    at cacheEntry.imageResponseCache.get.incrementalCache (/Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/server/next-server.js:181:76)
    at /Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/server/response-cache/index.js:90:42
    at async /Users/joshlong/Documents/repos/forks/getlit/testing/node_modules/next/dist/lib/batcher.js:41:32
```

Looks to be the same issue of not being able to find the image cache. but on a glance it looks like `fetch` is being called server side through an `ipc` invokation. maybe it should be using `node-fetch` to support this call?

**Comment by joshLong145** [comment]
One little thing is that we just released version `3.1.1` into beta which has our main nets supported. could we make the @lit-protocol package versions `3.1.1`

**Comment by yhl125** [comment]
@joshLong145 I think thats not react error.
In react there is no node_modules/next.
Maybe you didn't delete testing folder before pull.
Because the git init command is run on creation, the created folders are not tracked by getlit git.

I knew that 3.1.1 had been released, but I didn't upgrade because `capacityDelegationAuthSig` was added to `GetSessionSigsProps`, and I wasn't sure what `AuthSig` to put in. Can you provide an example?

**Comment by yhl125** [comment]
In the getSessionSigs function of the js-sdk:
```
  getSessionSigs = async (
    params: GetSessionSigsProps
  ): Promise<SessionSigsMap> => {
...
line 2824 lit-node-client-nodejs.ts
      const capabilities = params.capacityDelegationAuthSig
      ? [params.capacityDelegationAuthSig, authSig]
      : [authSig];
```
But in types 
```
export interface GetSessionSigsProps {
...
    capacityDelegationAuthSig: AuthSig;
}
```
I think you may want to make capacityDelegationAuthSig an optional prop, but it's not optional.
capabilities will always be [params.capacityDelegationAuthSig, authSig].

**Comment by joshLong145** [comment]
> In the getSessionSigs function of the js-sdk:
> 
> ```
>   getSessionSigs = async (
>     params: GetSessionSigsProps
>   ): Promise<SessionSigsMap> => {
> ...
> line 2824 lit-node-client-nodejs.ts
>       const capabilities = params.capacityDelegationAuthSig
>       ? [params.capacityDelegationAuthSig, authSig]
>       : [authSig];
> ```
> 
> But in types
> 
> ```
> export interface GetSessionSigsProps {
> ...
>     capacityDelegationAuthSig: AuthSig;
> }
> ```
> 
> I think you may want to make capacityDelegationAuthSig an optional prop, but it's not optional. when using ts, capabilities will be [params.capacityDelegationAuthSig, authSig].

This has been updated and will be published in `3.1.2`

**Comment by joshLong145** [comment]
> @joshLong145 I think thats not react error. In react there is no node_modules/next. Maybe you didn't delete testing folder before pull. Because the git init command is run on creation, the created folders are not tracked by getlit git.
> 
> I knew that 3.1.1 had been released, but I didn't upgrade because `capacityDelegationAuthSig` was added to `GetSessionSigsProps`, and I wasn't sure what `AuthSig` to put in. Can you provide an example?

So capacity credits are only needed on `main net networks` `cayenne` does not require capacity credits.
you can see here how to mint them, the wallet which mints them must sign an `authSig` which will be used as proof of capacity credits.

see here: https://developer.litprotocol.com/v3/sdk/capacity-credits

**Comment by joshLong145** [comment]
> @joshLong145 I think thats not react error. In react there is no node_modules/next. Maybe you didn't delete testing folder before pull. Because the git init command is run on creation, the created folders are not tracked by getlit git.
> 
> I knew that 3.1.1 had been released, but I didn't upgrade because `capacityDelegationAuthSig` was added to `GetSessionSigsProps`, and I wasn't sure what `AuthSig` to put in. Can you provide an example?

I think you are correct. this was actually a next issue but i no longer observe it.

**Comment by glitch003** [comment]
hey @yhl125 - quick ask.  could you split the vite config into a dev env and a prod env, and then include this plugin in the dev env?  https://github.com/liuweiGL/vite-plugin-mkcert

i'm having trouble running this on localhost in Chrome because it doesn't use HTTPs and then I get an "invalid origin: http" error when testing webauthn.  I did test this plugin locally and it seems to work great.

**Comment by yhl125** [comment]
> hey @yhl125 - quick ask. could you split the vite config into a dev env and a prod env, and then include this plugin in the dev env? https://github.com/liuweiGL/vite-plugin-mkcert
> 
> i'm having trouble running this on localhost in Chrome because it doesn't use HTTPs and then I get an "invalid origin: http" error when testing webauthn. I did test this plugin locally and it seems to work great.

In my case webauthn also works on http. However, I applied it as requested. I applied Conditional Application to plugins instead split config env.

**Comment by joshLong145** [comment]
> > hey @yhl125 - quick ask. could you split the vite config into a dev env and a prod env, and then include this plugin in the dev env? https://github.com/liuweiGL/vite-plugin-mkcert
> > i'm having trouble running this on localhost in Chrome because it doesn't use HTTPs and then I get an "invalid origin: http" error when testing webauthn. I did test this plugin locally and it seems to work great.
> 
> In my case webauthn also works on http. However, I applied it as requested. I applied Conditional Application to plugins instead split config env.

in some browsers such as Chrome `navigator.credential` will be restricted to `https` origins. It is up to the browser implementor to enforce this so it changes depending on the browser.
This looks great. Going to merge, thank you so much @yhl125

**Pull request merged**
